// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.repository;

import com.nrx.poc.domain.Attribute;
import com.nrx.poc.repository.AttributeRepository;
import java.math.BigInteger;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.stereotype.Repository;

privileged aspect AttributeRepository_Roo_Mongo_Repository {
    
    declare parents: AttributeRepository extends PagingAndSortingRepository<Attribute, BigInteger>;
    
    declare @type: AttributeRepository: @Repository;
    
}
