// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.repository;

import com.nrx.poc.domain.Location;
import com.nrx.poc.repository.LocationRepository;
import java.math.BigInteger;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.stereotype.Repository;

privileged aspect LocationRepository_Roo_Mongo_Repository {
    
    declare parents: LocationRepository extends PagingAndSortingRepository<Location, BigInteger>;
    
    declare @type: LocationRepository: @Repository;
    
}
