// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.domain;

import com.nrx.poc.domain.Attribute;
import com.nrx.poc.domain.AttributeDataOnDemand;
import com.nrx.poc.domain.AttributeValue;
import com.nrx.poc.domain.AttributeValueDataOnDemand;
import com.nrx.poc.repository.AttributeValueRepository;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AttributeValueDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AttributeValueDataOnDemand: @Component;
    
    private Random AttributeValueDataOnDemand.rnd = new SecureRandom();
    
    private List<AttributeValue> AttributeValueDataOnDemand.data;
    
    @Autowired
    AttributeDataOnDemand AttributeValueDataOnDemand.attributeDataOnDemand;
    
    @Autowired
    AttributeValueRepository AttributeValueDataOnDemand.attributeValueRepository;
    
    public AttributeValue AttributeValueDataOnDemand.getNewTransientAttributeValue(int index) {
        AttributeValue obj = new AttributeValue();
        setAttValue(obj, index);
        setAttribute(obj, index);
        return obj;
    }
    
    public void AttributeValueDataOnDemand.setAttValue(AttributeValue obj, int index) {
        String attValue = "attValue_" + index;
        obj.setAttValue(attValue);
    }
    
    public void AttributeValueDataOnDemand.setAttribute(AttributeValue obj, int index) {
        Attribute attribute = attributeDataOnDemand.getRandomAttribute();
        obj.setAttribute(attribute);
    }
    
    public AttributeValue AttributeValueDataOnDemand.getSpecificAttributeValue(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AttributeValue obj = data.get(index);
        BigInteger id = obj.getId();
        return attributeValueRepository.findOne(id);
    }
    
    public AttributeValue AttributeValueDataOnDemand.getRandomAttributeValue() {
        init();
        AttributeValue obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return attributeValueRepository.findOne(id);
    }
    
    public boolean AttributeValueDataOnDemand.modifyAttributeValue(AttributeValue obj) {
        return false;
    }
    
    public void AttributeValueDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = attributeValueRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AttributeValue' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AttributeValue>();
        for (int i = 0; i < 10; i++) {
            AttributeValue obj = getNewTransientAttributeValue(i);
            try {
                attributeValueRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
