// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.domain;

import com.nrx.poc.domain.AttributeValueDataOnDemand;
import com.nrx.poc.domain.AttributeValueIntegrationTest;
import com.nrx.poc.repository.AttributeValueRepository;
import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect AttributeValueIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AttributeValueIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AttributeValueIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    AttributeValueDataOnDemand AttributeValueIntegrationTest.dod;
    
    @Autowired
    AttributeValueRepository AttributeValueIntegrationTest.attributeValueRepository;
    
    @Test
    public void AttributeValueIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'AttributeValue' failed to initialize correctly", dod.getRandomAttributeValue());
        long count = attributeValueRepository.count();
        Assert.assertTrue("Counter for 'AttributeValue' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AttributeValueIntegrationTest.testFind() {
        AttributeValue obj = dod.getRandomAttributeValue();
        Assert.assertNotNull("Data on demand for 'AttributeValue' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AttributeValue' failed to provide an identifier", id);
        obj = attributeValueRepository.findOne(id);
        Assert.assertNotNull("Find method for 'AttributeValue' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AttributeValue' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AttributeValueIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'AttributeValue' failed to initialize correctly", dod.getRandomAttributeValue());
        long count = attributeValueRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'AttributeValue', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AttributeValue> result = attributeValueRepository.findAll();
        Assert.assertNotNull("Find all method for 'AttributeValue' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AttributeValue' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AttributeValueIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'AttributeValue' failed to initialize correctly", dod.getRandomAttributeValue());
        long count = attributeValueRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AttributeValue> result = attributeValueRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'AttributeValue' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AttributeValue' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AttributeValueIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'AttributeValue' failed to initialize correctly", dod.getRandomAttributeValue());
        AttributeValue obj = dod.getNewTransientAttributeValue(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AttributeValue' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AttributeValue' identifier to be null", obj.getId());
        try {
            attributeValueRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'AttributeValue' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AttributeValueIntegrationTest.testDelete() {
        AttributeValue obj = dod.getRandomAttributeValue();
        Assert.assertNotNull("Data on demand for 'AttributeValue' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AttributeValue' failed to provide an identifier", id);
        obj = attributeValueRepository.findOne(id);
        attributeValueRepository.delete(obj);
        Assert.assertNull("Failed to remove 'AttributeValue' with identifier '" + id + "'", attributeValueRepository.findOne(id));
    }
    
}
