// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.domain;

import com.nrx.poc.domain.LocationDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect LocationDataOnDemand_Roo_Configurable {
    
    declare @type: LocationDataOnDemand: @Configurable;
    
}
