// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.domain;

import com.nrx.poc.domain.LocationDataOnDemand;
import com.nrx.poc.domain.LocationIntegrationTest;
import com.nrx.poc.repository.LocationRepository;
import java.math.BigInteger;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect LocationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LocationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LocationIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    LocationDataOnDemand LocationIntegrationTest.dod;
    
    @Autowired
    LocationRepository LocationIntegrationTest.locationRepository;
    
    @Test
    public void LocationIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Location' failed to initialize correctly", dod.getRandomLocation());
        long count = locationRepository.count();
        Assert.assertTrue("Counter for 'Location' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LocationIntegrationTest.testFind() {
        Location obj = dod.getRandomLocation();
        Assert.assertNotNull("Data on demand for 'Location' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Location' failed to provide an identifier", id);
        obj = locationRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Location' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Location' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LocationIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Location' failed to initialize correctly", dod.getRandomLocation());
        long count = locationRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Location', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Location> result = locationRepository.findAll();
        Assert.assertNotNull("Find all method for 'Location' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Location' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LocationIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Location' failed to initialize correctly", dod.getRandomLocation());
        long count = locationRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Location> result = locationRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Location' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Location' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LocationIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Location' failed to initialize correctly", dod.getRandomLocation());
        Location obj = dod.getNewTransientLocation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Location' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Location' identifier to be null", obj.getId());
        try {
            locationRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        Assert.assertNotNull("Expected 'Location' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LocationIntegrationTest.testDelete() {
        Location obj = dod.getRandomLocation();
        Assert.assertNotNull("Data on demand for 'Location' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Location' failed to provide an identifier", id);
        obj = locationRepository.findOne(id);
        locationRepository.delete(obj);
        Assert.assertNull("Failed to remove 'Location' with identifier '" + id + "'", locationRepository.findOne(id));
    }
    
}
