// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.domain;

import com.nrx.poc.domain.Attribute;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Attribute_Roo_Json {
    
    public String Attribute.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public String Attribute.toJson(String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").serialize(this);
    }
    
    public static Attribute Attribute.fromJsonToAttribute(String json) {
        return new JSONDeserializer<Attribute>().use(null, Attribute.class).deserialize(json);
    }
    
    public static String Attribute.toJsonArray(Collection<Attribute> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static String Attribute.toJsonArray(Collection<Attribute> collection, String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").serialize(collection);
    }
    
    public static Collection<Attribute> Attribute.fromJsonArrayToAttributes(String json) {
        return new JSONDeserializer<List<Attribute>>().use(null, ArrayList.class).use("values", Attribute.class).deserialize(json);
    }
    
}
