// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.domain;

import com.nrx.poc.domain.AttributeValue;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect AttributeValue_Roo_Json {
    
    public String AttributeValue.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public String AttributeValue.toJson(String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").serialize(this);
    }
    
    public static AttributeValue AttributeValue.fromJsonToAttributeValue(String json) {
        return new JSONDeserializer<AttributeValue>().use(null, AttributeValue.class).deserialize(json);
    }
    
    public static String AttributeValue.toJsonArray(Collection<AttributeValue> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static String AttributeValue.toJsonArray(Collection<AttributeValue> collection, String[] fields) {
        return new JSONSerializer().include(fields).exclude("*.class").serialize(collection);
    }
    
    public static Collection<AttributeValue> AttributeValue.fromJsonArrayToAttributeValues(String json) {
        return new JSONDeserializer<List<AttributeValue>>().use(null, ArrayList.class).use("values", AttributeValue.class).deserialize(json);
    }
    
}
