// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.domain;

import com.nrx.poc.domain.AttributeValue;
import java.math.BigInteger;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Persistent;

privileged aspect AttributeValue_Roo_Mongo_Entity {
    
    declare @type: AttributeValue: @Persistent;
    
    @Id
    private BigInteger AttributeValue.id;
    
    public BigInteger AttributeValue.getId() {
        return this.id;
    }
    
    public void AttributeValue.setId(BigInteger id) {
        this.id = id;
    }
    
}
