// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.domain;

import com.nrx.poc.domain.Attribute;

privileged aspect Attribute_Roo_JavaBean {
    
    public String Attribute.getName() {
        return this.name;
    }
    
    public void Attribute.setName(String name) {
        this.name = name;
    }
    
}
