// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.domain;

import com.nrx.poc.domain.Attribute;
import com.nrx.poc.domain.AttributeValue;

privileged aspect AttributeValue_Roo_JavaBean {
    
    public String AttributeValue.getAttValue() {
        return this.attValue;
    }
    
    public void AttributeValue.setAttValue(String attValue) {
        this.attValue = attValue;
    }
    
    public Attribute AttributeValue.getAttribute() {
        return this.attribute;
    }
    
    public void AttributeValue.setAttribute(Attribute attribute) {
        this.attribute = attribute;
    }
    
}
