// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.domain;

import com.nrx.poc.domain.AttributeValue;
import com.nrx.poc.domain.Location;
import java.util.Set;

privileged aspect Location_Roo_JavaBean {
    
    public String Location.getErpCode() {
        return this.erpCode;
    }
    
    public void Location.setErpCode(String erpCode) {
        this.erpCode = erpCode;
    }
    
    public String Location.getName() {
        return this.name;
    }
    
    public void Location.setName(String name) {
        this.name = name;
    }
    
    public String Location.getTag() {
        return this.tag;
    }
    
    public void Location.setTag(String tag) {
        this.tag = tag;
    }
    
    public Integer Location.getSerialNumber() {
        return this.serialNumber;
    }
    
    public void Location.setSerialNumber(Integer serialNumber) {
        this.serialNumber = serialNumber;
    }
    
    public String Location.getPlant() {
        return this.plant;
    }
    
    public void Location.setPlant(String plant) {
        this.plant = plant;
    }
    
    public Set<AttributeValue> Location.getAttributeValues() {
        return this.attributeValues;
    }
    
    public void Location.setAttributeValues(Set<AttributeValue> attributeValues) {
        this.attributeValues = attributeValues;
    }
    
}
