// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.web;

import com.nrx.poc.domain.Attribute;
import com.nrx.poc.domain.AttributeValue;
import com.nrx.poc.repository.AttributeRepository;
import com.nrx.poc.repository.AttributeValueRepository;
import com.nrx.poc.web.AttributeValueController;
import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect AttributeValueController_Roo_Controller {
    
    @Autowired
    AttributeValueRepository AttributeValueController.attributeValueRepository;
    
    @Autowired
    AttributeRepository AttributeValueController.attributeRepository;
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String AttributeValueController.create(@Valid AttributeValue attributeValue, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, attributeValue);
            return "attributevalues/create";
        }
        uiModel.asMap().clear();
        attributeValueRepository.save(attributeValue);
        return "redirect:/attributevalues/" + encodeUrlPathSegment(attributeValue.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String AttributeValueController.createForm(Model uiModel) {
        populateEditForm(uiModel, new AttributeValue());
        List<String[]> dependencies = new ArrayList<String[]>();
        if (attributeRepository.count() == 0) {
            dependencies.add(new String[] { "attribute", "attributes" });
        }
        uiModel.addAttribute("dependencies", dependencies);
        return "attributevalues/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String AttributeValueController.show(@PathVariable("id") BigInteger id, Model uiModel) {
        uiModel.addAttribute("attributevalue", attributeValueRepository.findOne(id));
        uiModel.addAttribute("itemId", id);
        return "attributevalues/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String AttributeValueController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("attributevalues", attributeValueRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / sizeNo, sizeNo)).getContent());
            float nrOfPages = (float) attributeValueRepository.count() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("attributevalues", attributeValueRepository.findAll());
        }
        return "attributevalues/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String AttributeValueController.update(@Valid AttributeValue attributeValue, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, attributeValue);
            return "attributevalues/update";
        }
        uiModel.asMap().clear();
        attributeValueRepository.save(attributeValue);
        return "redirect:/attributevalues/" + encodeUrlPathSegment(attributeValue.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String AttributeValueController.updateForm(@PathVariable("id") BigInteger id, Model uiModel) {
        populateEditForm(uiModel, attributeValueRepository.findOne(id));
        return "attributevalues/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String AttributeValueController.delete(@PathVariable("id") BigInteger id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        AttributeValue attributeValue = attributeValueRepository.findOne(id);
        attributeValueRepository.delete(attributeValue);
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/attributevalues";
    }
    
    void AttributeValueController.populateEditForm(Model uiModel, AttributeValue attributeValue) {
        uiModel.addAttribute("attributeValue", attributeValue);
        uiModel.addAttribute("attributes", attributeRepository.findAll());
    }
    
    String AttributeValueController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
