// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nrx.poc.web;

import com.nrx.poc.domain.AttributeValue;
import com.nrx.poc.web.AttributeValueController;
import java.math.BigInteger;
import java.util.List;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

privileged aspect AttributeValueController_Roo_Controller_Json {
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET, headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> AttributeValueController.showJson(@PathVariable("id") BigInteger id) {
        AttributeValue attributeValue = attributeValueRepository.findOne(id);
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json; charset=utf-8");
        if (attributeValue == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<String>(attributeValue.toJson(), headers, HttpStatus.OK);
    }
    
    @RequestMapping(headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> AttributeValueController.listJson() {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json; charset=utf-8");
        List<AttributeValue> result = attributeValueRepository.findAll();
        return new ResponseEntity<String>(AttributeValue.toJsonArray(result), headers, HttpStatus.OK);
    }
    
    @RequestMapping(method = RequestMethod.POST, headers = "Accept=application/json")
    public ResponseEntity<String> AttributeValueController.createFromJson(@RequestBody String json) {
        AttributeValue attributeValue = AttributeValue.fromJsonToAttributeValue(json);
        attributeValueRepository.save(attributeValue);
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        return new ResponseEntity<String>(headers, HttpStatus.CREATED);
    }
    
    @RequestMapping(value = "/jsonArray", method = RequestMethod.POST, headers = "Accept=application/json")
    public ResponseEntity<String> AttributeValueController.createFromJsonArray(@RequestBody String json) {
        for (AttributeValue attributeValue: AttributeValue.fromJsonArrayToAttributeValues(json)) {
            attributeValueRepository.save(attributeValue);
        }
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        return new ResponseEntity<String>(headers, HttpStatus.CREATED);
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.PUT, headers = "Accept=application/json")
    public ResponseEntity<String> AttributeValueController.updateFromJson(@RequestBody String json, @PathVariable("id") BigInteger id) {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        AttributeValue attributeValue = AttributeValue.fromJsonToAttributeValue(json);
        if (attributeValueRepository.save(attributeValue) == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<String>(headers, HttpStatus.OK);
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, headers = "Accept=application/json")
    public ResponseEntity<String> AttributeValueController.deleteFromJson(@PathVariable("id") BigInteger id) {
        AttributeValue attributeValue = attributeValueRepository.findOne(id);
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/json");
        if (attributeValue == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        attributeValueRepository.delete(attributeValue);
        return new ResponseEntity<String>(headers, HttpStatus.OK);
    }
    
}
